/* StoryForge V4.6 — portable export + print for image refs */
(() => {
  'use strict';
  const CRC_TABLE=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>8;t[n]=c>>>0;}return t;})();
  function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=CRC_TABLE[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
  function u16(n){return new Uint8Array([n&255,(n>>>8)&255]);}
  function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);}
  function join(parts){const size=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(size);let at=0;for(const p of parts){out.set(p,at);at+=p.length;}return out;}
  function makeZip(entries){const enc=new TextEncoder(),locals=[],centrals=[];let offset=0;for(const entry of entries){const name=enc.encode(entry.name),data=entry.data instanceof Uint8Array?entry.data:new Uint8Array(entry.data),crc=crc32(data);const local=join([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);const central=join([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]);centrals.push(central);offset+=local.length;}const centralSize=centrals.reduce((n,p)=>n+p.length,0),end=join([u32(0x06054b50),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(centralSize),u32(offset),u16(0)]);return new Blob([...locals,...centrals,end],{type:'application/zip'});}
  function extFor(rec){const n=(rec?.name||'').toLowerCase(),m=rec?.mime||rec?.blob?.type||'';const hit=n.match(/\.([a-z0-9]{2,5})$/);if(hit)return hit[1]==='jpeg'?'jpg':hit[1];if(m==='image/png')return'png';if(m==='image/jpeg')return'jpg';if(m==='image/webp')return'webp';if(m==='image/gif')return'gif';return'bin';}
  function assetPath(p,c,rec){const pn=String(p.numero).padStart(2,'0'),raw=String(c.numero),clean=raw.toLowerCase().replace(/[^a-z0-9]+/g,'')||c.id.toLowerCase().replace(/[^a-z0-9]+/g,''),cn=/^\d+$/.test(clean)?clean.padStart(2,'0'):clean.replace(/^(\d)(\D)/,'0$1$2');return `assets/bd/p${pn}/c${cn}.${extFor(rec)}`;}
  function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

  window.exportProd=async function(){try{const enc=new TextEncoder(),records=await dbAll(),byId=new Map(records.map(r=>[r.id,r])),portable=clone(SEED),entries=[],manifest=[];for(const p of portable.planches||[])for(const c of p.cases||[]){if(!String(c.image||'').startsWith('idb://'))continue;const id=c.image.slice(6),rec=byId.get(id);if(!rec?.blob)throw new Error(`Image IndexedDB introuvable : ${c.id}`);const path=assetPath(p,c,rec);entries.push({name:path,data:await rec.blob.arrayBuffer()});manifest.push({case_id:c.id,source:c.image,target:'./'+path,name:rec.name||null});c.image='./'+path;}entries.unshift({name:'storyforge-v46-seed-travail.json',data:enc.encode(JSON.stringify(portable,null,2))},{name:'integration-manifest.json',data:enc.encode(JSON.stringify({exported_at:new Date().toISOString(),files:manifest},null,2))});download(makeZip(entries),'storyforge-v46-export.zip');toast('Archive ZIP exportée');}catch(err){alert('Export impossible : '+err.message);}};

  window.buildPrint=async function(plancheId){const pages=plancheId?SEED.planches.filter(p=>p.id===plancheId):SEED.planches,blocks=[];for(const p of pages){const cases=[];for(const c of p.cases||[]){const img=await resolveImageRef(c.image);cases.push(`<div class="c"><b>Case ${esc(c.numero)}${c.titre?' — '+esc(c.titre):''}</b>${img?`<div class="printcanvas"><img class="printimg" src="${img}" alt="">${(c.overlays||[]).map(o=>overlayHTML(p,c,o)).join('')}</div>`:''}${c.description?`<p>${esc(c.description)}</p>`:''}${(c.textes||[]).map(t=>`<div class="tx ${t.preserve_exact?'locked-print':''}"><i>${esc(typeInfo(t.type)[1])}${t.personnage_id?' '+esc(t.personnage_id):''}${t.preserve_exact?' 🔒':''} :</i> ${esc(t.contenu)}</div>`).join('')}${c.personnages?.length?`<p><i>Personnages : ${esc(c.personnages.join(', '))}</i></p>`:''}</div>`);}blocks.push(`<div class="pl"><h2>Planche ${esc(p.numero)} — ${esc(p.titre)}</h2><div class="g">${esc(p.chapitre||'')}${p.date_histoire?' · '+esc(p.date_histoire):''}</div>${cases.join('')}</div>`);}document.getElementById('printArea').innerHTML=`<h1>${esc(SEED.projet.titre)} — ${esc(SEED.projet.version)}</h1><div class="psub">Storyboard de production · ${pages.length} planche(s) · texte et images</div>${blocks.join('')}`;};
})();