import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { chromium } from "playwright";

const base = process.env.STORYFORGE_TEST_URL || "http://127.0.0.1:8080";
if (!["127.0.0.1", "localhost"].includes(new URL(base).hostname)) throw new Error("Local app required");
const output = process.env.STORYFORGE_TEST_OUTPUT || "/workspace/screenshots/storyforge";
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.STORYFORGE_CHROMIUM ? { executablePath: process.env.STORYFORGE_CHROMIUM } : {}), args: ["--no-sandbox", "--disable-dev-shm-usage"] });
try {
  for (const width of [390, 1280]) {
    const context = await browser.newContext({ viewport: { width, height: 844 } });
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", (error) => errors.push(error.message));
    page.on("dialog", (dialog) => dialog.accept());
    await page.goto(base, { waitUntil: "domcontentloaded" });
    await page.getByRole("heading", { name: "Projets", exact: true }).waitFor();
    await page.getByRole("button", { name: /Nous, malgré nous/ }).click();
    await page.getByRole("heading", { name: "Planches visuelles" }).waitFor();
    assert.ok(await page.getByRole("link", { name: /Planche 01/ }).count());
    assert.equal(await page.getByText("Chapitres", { exact: true }).count(), 0);
    await page.getByRole("link", { name: "Personnages & règles" }).click();
    await page.waitForFunction(() => document.querySelectorAll("article img.object-contain").length === 5);
    assert.equal(await page.locator("article img.object-contain").first().evaluate((img) => getComputedStyle(img).objectFit), "contain");
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByRole("link", { name: /Planche 01/ }).click();
    const image = page.locator(".visual-grid img").first();
    await image.waitFor();
    assert.equal(await image.evaluate((img) => getComputedStyle(img).objectFit), "cover");
    const originalId = await page.evaluate(() => JSON.parse(localStorage.getItem("sf46-seed")).cases[0].id);
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByRole("button", { name: "Ajouter une case", exact: true }).click();
    const inspector = page.getByRole("dialog", { name: /^Case \d+$/ });
    await inspector.getByLabel("Mise en image").fill("Case mobile à déplacer");
    await inspector.getByLabel("Note", { exact: true }).fill("Note préservée");
    await inspector.getByText("Options avancées").click();
    await inspector.getByLabel("Largeur grille").selectOption("3");
    await inspector.getByLabel("Hauteur grille").selectOption("4");
    const id = await page.evaluate(() => JSON.parse(localStorage.getItem("sf46-seed")).cases.at(-1).id);
    await inspector.getByRole("button", { name: "Fermer" }).click();
    assert.equal(await page.locator(".visual-grid").count(), 1);
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByText(/Ordre du récit · 153 cases/).click();
    await page.locator("li").filter({ hasText: "Case mobile à déplacer" }).getByRole("button", { name: /Déplacer case/ }).click();
    const moving = page.getByRole("dialog", { name: /^Déplacer Case/ });
    await moving.getByLabel("Position").selectOption("before");
    await moving.getByLabel("Case de référence").selectOption(originalId);
    await moving.getByRole("button", { name: "Déplacer la case" }).click();
    await page.waitForFunction((caseId) => JSON.parse(localStorage.getItem("sf46-seed")).cases[0].id === caseId, id);
    await page.reload();
    await page.getByRole("heading", { name: "Planches visuelles" }).waitFor();
    const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("sf46-seed")));
    assert.equal(saved.cases[0].id, id);
    assert.equal(saved.cases[0].description, "Case mobile à déplacer");
    assert.equal(saved.cases[0].notes, "Note préservée");
    assert.deepEqual(saved.cases[0].layout_size, { width: 3, height: 4 });
    assert.equal(saved.cases[1].id, originalId);
    assert.equal(saved.planches.every((p) => p.cases.length === 0), true);
    assert.equal(Object.hasOwn(saved.cases[0], "numero"), false);
    await page.getByRole("link", { name: /Planche 01/ }).click();
    assert.equal(await page.locator(".visual-grid > div").count(), 1);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.deepEqual(errors, []);
    await page.screenshot({ path: join(output, `page-${width}.png`), animations: "disabled" });
    console.log(`PASS ${width}px: mobile move, editor return, 3×4 grid, image fit and persistence`);
    await context.close();
  }
} finally { await browser.close(); }
