import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { chromium } from "playwright";

const base = process.env.STORYFORGE_TEST_URL || "http://127.0.0.1:8080";
if (!["127.0.0.1", "localhost"].includes(new URL(base).hostname)) throw new Error("Local app required");
const output = process.env.STORYFORGE_TEST_OUTPUT || "/workspace/screenshots/storyforge";
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.STORYFORGE_CHROMIUM ? { executablePath: process.env.STORYFORGE_CHROMIUM } : {}), args: ["--no-sandbox", "--disable-dev-shm-usage"] });
try {
  for (const width of [390, 1280]) {
    const context = await browser.newContext({ viewport: { width, height: 844 } });
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", (e) => errors.push(e.message));
    page.on("dialog", (d) => d.accept());
    await page.goto(base, { waitUntil: "domcontentloaded" });
    await page.getByRole("heading", { name: "Projets", exact: true }).waitFor();
    await page.getByRole("button", { name: /Nous, malgré nous/ }).waitFor();
    for (const name of ["Accueil", "Bibliothèque", "Profil", "Chapitres"]) assert.equal(await page.getByText(name, { exact: true }).count(), 0);
    assert.equal(await page.locator("nav").count(), 0);
    await page.screenshot({ path: join(output, `projects-${width}.png`), animations: "disabled" });
    await page.getByRole("button", { name: /Nous, malgré nous/ }).click();
    await page.getByRole("heading", { name: "Nous, malgré nous" }).waitFor();
    assert.equal(await page.getByRole("button", { name: "Actions" }).count(), 29);
    await page.getByRole("link", { name: "Personnages & règles" }).click();
    await page.getByRole("button", { name: "Remplacer l’image" }).first().waitFor();
    await page.waitForFunction(() => document.querySelectorAll("article img.object-contain").length === 5);
    assert.equal(await page.locator("article img.object-contain").count(), 5);
    assert.equal(await page.locator("article img.object-contain").first().evaluate((img) => getComputedStyle(img).objectFit), "contain");
    const person = page.locator("article").first();
    await person.getByLabel("Rôle").fill("Rôle navigateur");
    await person.getByLabel("Description").fill("Description navigateur");
    await page.getByText("Règles", { exact: true }).click();
    await page.getByLabel("Contenu").first().fill("Règle navigateur");
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByText("MÉTRO PAPINEAU", { exact: true }).click();
    await page.getByRole("button", { name: "Ajouter une case", exact: true }).click();
    const inspector = page.getByRole("dialog", { name: /^Case \d+$/ });
    await inspector.getByLabel("Mise en image").fill("Case mobile à déplacer");
    await inspector.getByLabel("Note", { exact: true }).fill("Note préservée");
    await inspector.getByText("Options avancées").click();
    await inspector.getByLabel("Largeur grille").selectOption("2");
    await page.waitForFunction(() => {
      const seed = JSON.parse(localStorage.getItem("sf46-seed") || "null");
      return seed?.planches?.[0]?.cases?.some((c) => c.description === "Case mobile à déplacer" && c.layout_size?.width === 2);
    });
    const id = await page.evaluate(() => {
      const seed = JSON.parse(localStorage.getItem("sf46-seed") || "null");
      return seed?.planches?.[0]?.cases?.at(-1)?.id;
    });
    await inspector.getByRole("button", { name: "Fermer" }).click();
    assert.equal(await page.locator(".visual-grid").count(), 1);
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByText(/Ordre du récit · 153 cases/).click();
    const source = page.locator("li").filter({ hasText: "Case mobile à déplacer" });
    await source.getByRole("button", { name: /Déplacer case/ }).click();
    const moving = page.getByRole("dialog", { name: /^Déplacer Case/ });
    await moving.getByLabel("Position").selectOption("before");
    const firstId = await moving.getByLabel("Case de référence").locator("option").first().getAttribute("value");
    await moving.getByLabel("Case de référence").selectOption(firstId);
    await moving.getByRole("button", { name: "Déplacer la case" }).click();
    await page.waitForFunction((caseId) => {
      const seed = JSON.parse(localStorage.getItem("sf46-seed") || "null");
      return seed?.ordre_cases?.[0] === caseId;
    }, id);
    let seed = await page.evaluate(() => JSON.parse(localStorage.getItem("sf46-seed")));
    assert.equal(seed.planches[0].cases[0].id, id);
    assert.equal(seed.planches[0].cases[0].numero, "1");
    assert.equal(seed.planches[0].cases[0].description, "Case mobile à déplacer");
    assert.equal(seed.planches[0].cases[0].notes, "Note préservée");
    assert.equal(seed.planches[0].cases[0].layout_size.width, 2);
    assert.equal(seed.personnages[0].role, "Rôle navigateur");
    assert.equal(seed.regles_editoriales[0].contenu, "Règle navigateur");
    await page.reload();
    await page.getByRole("heading", { name: "Nous, malgré nous" }).waitFor();
    seed = await page.evaluate(() => JSON.parse(localStorage.getItem("sf46-seed")));
    assert.equal(seed.ordre_cases[0], id);
    assert.equal(seed.planches[0].cases[0].description, "Case mobile à déplacer");
    await page.getByRole("link", { name: "Retour aux projets" }).click();
    await page.getByRole("button", { name: "Nouveau projet" }).click();
    await page.getByRole("dialog", { name: "Nouveau projet" }).getByLabel("Nom du projet").fill("Projet QA");
    await page.getByRole("button", { name: "Créer le projet" }).click();
    await page.getByText("Aucune planche pour ce filtre.").waitFor();
    await page.getByRole("button", { name: "Nouvelle planche" }).click();
    await page.getByRole("button", { name: "Ajouter une case", exact: true }).click();
    await page.getByRole("dialog", { name: "Case 1" }).getByRole("button", { name: "Fermer" }).click();
    assert.equal(await page.locator(".visual-grid").count(), 1);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.deepEqual(errors, []);
    await page.screenshot({ path: join(output, `page-${width}.png`), animations: "disabled" });
    console.log(`PASS ${width}px: projects → project → page → case, edits, images, move before Case 1, reload, mobile overflow, console`);
    await context.close();
  }
} finally { await browser.close(); }
