import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { chromium } from "playwright";

const base = process.env.STORYFORGE_TEST_URL || "http://127.0.0.1:8080";
if (!["127.0.0.1", "localhost"].includes(new URL(base).hostname)) throw new Error("Local app required");
const output = process.env.STORYFORGE_TEST_OUTPUT || "/workspace/screenshots/storyforge";
await mkdir(output, { recursive: true });
const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL/nwAAAABJRU5ErkJggg==", "base64");
const browser = await chromium.launch({ headless: true, ...(process.env.STORYFORGE_CHROMIUM ? { executablePath: process.env.STORYFORGE_CHROMIUM } : {}), args: ["--no-sandbox", "--disable-dev-shm-usage"] });
try {
  for (const width of [390, 1280]) {
    const context = await browser.newContext({ viewport: { width, height: 844 } });
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", (error) => errors.push(error.message));
    page.on("dialog", (dialog) => dialog.accept());
    await page.goto(base, { waitUntil: "domcontentloaded" });
    await page.getByRole("heading", { name: "Projets", exact: true }).waitFor();
    for (const name of ["Accueil", "Bibliothèque", "Profil", "Chapitres"])
      assert.equal(await page.getByText(name, { exact: true }).count(), 0);
    assert.equal(await page.locator("nav").count(), 0);
    await page.getByRole("button", { name: /Nous, malgré nous/ }).click();
    await page.getByRole("heading", { name: "Planches visuelles" }).waitFor();
    assert.ok(await page.getByRole("link", { name: /Planche 01/ }).count());
    assert.equal(await page.getByText("Chapitres", { exact: true }).count(), 0);
    await page.getByRole("link", { name: "Personnages & règles" }).click();
    await page.waitForFunction(() => document.querySelectorAll("article img.object-contain").length === 5);
    assert.equal(await page.locator("article img.object-contain").first().evaluate((img) => getComputedStyle(img).objectFit), "contain");
    await page.locator("article").first().getByLabel("Rôle").fill("Rôle navigateur");
    await page.locator("article").first().getByLabel("Description").fill("Description navigateur");
    await page.locator("article").nth(3).getByLabel("Fonction protectrice").fill("Protection navigateur");
    await page.getByText("Règles", { exact: true }).click();
    await page.getByLabel("Contenu").first().fill("Règle navigateur");
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByRole("link", { name: /Planche 01/ }).click();
    const image = page.locator(".visual-grid img").first();
    await image.waitFor();
    assert.equal(await image.evaluate((img) => getComputedStyle(img).objectFit), "cover");
    const originalId = "P01-1";
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByRole("button", { name: "Ajouter une case", exact: true }).click();
    const inspector = page.getByRole("dialog", { name: /^Case \d+$/ });
    await inspector.getByLabel("Mise en image").fill("Case mobile à déplacer");
    await inspector.getByLabel("Note", { exact: true }).fill("Note préservée");
    await inspector.getByText("Options avancées").click();
    await inspector.getByLabel("Largeur grille").selectOption("3");
    await inspector.getByLabel("Hauteur grille").selectOption("4");
    await inspector.getByRole("button", { name: "À valider" }).click();
    await inspector.getByRole("button", { name: "Bulle", exact: true }).click();
    await inspector.getByLabel("Contenu libre").fill("Bulle navigateur");
    const chooser = page.waitForEvent("filechooser");
    await inspector.getByRole("button", { name: "Ajouter une image" }).click();
    await (await chooser).setFiles({ name: "case-test.png", mimeType: "image/png", buffer: png });
    await page.waitForFunction(() => {
      const saved = JSON.parse(localStorage.getItem("sf46-seed") || "null");
      return saved?.cases?.length === 153 && saved.cases.some((c) => c.description === "Case mobile à déplacer" && c.layout_size?.height === 4 && c.image?.startsWith("idb://") && c.overlays?.[0]?.content === "Bulle navigateur" && c.statut === "brouillon");
    });
    const id = await page.evaluate(() => JSON.parse(localStorage.getItem("sf46-seed")).cases.at(-1).id);
    await inspector.getByRole("button", { name: "Fermer" }).click();
    assert.equal(await page.locator(".visual-grid").count(), 1);
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByText(/Ordre du récit · 153 cases/).click();
    await page.locator("li").filter({ hasText: "Case mobile à déplacer" }).getByRole("button", { name: /Déplacer case/ }).click();
    const moving = page.getByRole("dialog", { name: /^Déplacer Case/ });
    await moving.getByLabel("Position").selectOption("before");
    await moving.getByLabel("Case de référence").selectOption(originalId);
    await moving.getByRole("button", { name: "Déplacer la case" }).click();
    await page.waitForFunction((caseId) => JSON.parse(localStorage.getItem("sf46-seed")).cases[0].id === caseId, id);
    await page.reload();
    await page.getByRole("heading", { name: "Planches visuelles" }).waitFor();
    const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("sf46-seed")));
    assert.equal(saved.cases[0].id, id);
    assert.equal(saved.cases[0].description, "Case mobile à déplacer");
    assert.equal(saved.cases[0].notes, "Note préservée");
    assert.equal(saved.cases[0].statut, "brouillon");
    assert.equal(saved.cases[0].overlays[0].content, "Bulle navigateur");
    assert.equal(saved.cases[0].source_planche_id, "P29");
    assert.equal(saved.cases[0].gardien_override.armurier.present, false);
    assert.ok(saved.cases[0].image.startsWith("idb://"));
    assert.deepEqual(saved.cases[0].layout_size, { width: 3, height: 4 });
    assert.equal(saved.cases[1].id, originalId);
    assert.equal(saved.planches.every((p) => p.cases.length === 0), true);
    assert.equal(saved.personnages[0].role, "Rôle navigateur");
    assert.equal(saved.gardiens[0].fonction_protectrice, "Protection navigateur");
    assert.equal(saved.regles_editoriales[0].contenu, "Règle navigateur");
    assert.equal(Object.hasOwn(saved.cases[0], "numero"), false);
    await page.getByRole("link", { name: /Planche 01/ }).click();
    await page.locator(".visual-grid > div").first().waitFor();
    assert.equal(await page.locator(".visual-grid > div").count(), 1);
    assert.equal(await page.locator(".visual-grid img").first().evaluate((img) => getComputedStyle(img).objectFit), "cover");
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByRole("button", { name: "Rechercher" }).click();
    const search = page.getByRole("dialog", { name: "Rechercher dans le manuscrit" });
    await search.getByPlaceholder("Case, personnage…").fill("Case mobile à déplacer");
    await search.getByRole("button", { name: /Case 1/ }).click();
    await page.getByRole("dialog", { name: "Case 1" }).waitFor();
    await page.getByRole("dialog", { name: "Case 1" }).getByRole("button", { name: "Fermer" }).click();
    await page.getByRole("link", { name: "Retour au projet" }).click();
    const projectPageCount = page.getByRole("heading", { name: /^Planches visuelles · \d+$/ });
    await projectPageCount.waitFor();
    const visualPageCount = (await projectPageCount.textContent()).match(/\d+$/)?.[0];
    assert.ok(visualPageCount);
    await page.getByRole("link", { name: "Exporter" }).click();
    await page.getByText(`${visualPageCount} planches visuelles · 153 cases`, { exact: false }).waitFor();
    await page.evaluate(() => { window.print = () => {}; });
    await page.getByText("Storyboard complet").locator("../..").getByRole("button", { name: "Imprimer" }).click();
    await page.waitForFunction(() => document.querySelector("#print-root")?.textContent?.includes("Case mobile à déplacer"));
    assert.match(await page.locator("#print-root").textContent(), /Planche visuelle 1[\s\S]*Case 1/);
    const sessionDownload = page.waitForEvent("download");
    await page.getByText("Sauvegarder la session").locator("../..").getByRole("button", { name: "Exporter" }).click();
    const sessionPath = join(output, `session-${width}.json`);
    await (await sessionDownload).saveAs(sessionPath);
    const zipDownload = page.waitForEvent("download");
    await page.getByText("Export du projet").locator("../..").getByRole("button", { name: "OK" }).click();
    await (await zipDownload).saveAs(join(output, `project-${width}.zip`));
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByRole("link", { name: /Planche 01/ }).click();
    await page.locator(".visual-grid > div").first().getByRole("button").click();
    await page.getByRole("dialog", { name: "Case 1" }).getByLabel("Mise en image").fill("Modification temporaire");
    await page.getByRole("dialog", { name: "Case 1" }).getByRole("button", { name: "Fermer" }).click();
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByRole("link", { name: "Exporter" }).click();
    const restoreChooser = page.waitForEvent("filechooser");
    await page.getByText("Restaurer une sauvegarde").locator("../..").getByRole("button", { name: "Choisir" }).click();
    await (await restoreChooser).setFiles(sessionPath);
    await page.waitForFunction((caseId) => {
      const c = JSON.parse(localStorage.getItem("sf46-seed") || "null")?.cases?.[0];
      return c?.id === caseId && c?.description === "Case mobile à déplacer";
    }, id);
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByRole("link", { name: "Retour aux projets" }).click();
    await page.getByRole("button", { name: "Nouveau projet" }).click();
    await page.getByRole("dialog", { name: "Nouveau projet" }).getByLabel("Nom du projet").fill("Projet QA");
    await page.getByRole("button", { name: "Créer le projet" }).click();
    await page.getByText("Aucune case pour l’instant.").waitFor();
    await page.getByRole("button", { name: "Ajouter une case", exact: true }).click();
    const emptyInspector = page.getByRole("dialog", { name: "Case 1" });
    await emptyInspector.getByRole("button", { name: "Supprimer la case" }).click();
    await page.getByRole("link", { name: "Retour au projet" }).click();
    await page.getByText("Aucune case pour l’instant.").waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.deepEqual(errors, []);
    await page.screenshot({ path: join(output, `page-${width}.png`), animations: "disabled" });
    console.log(`PASS ${width}px: mobile move, editor return, 3×4 grid, image fit and persistence`);
    await context.close();
  }
} finally { await browser.close(); }
