/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as BibliothequeRouteImport } from './routes/bibliotheque'
import { Route as DonneesRouteImport } from './routes/donnees'
import { Route as ProjetRouteImport } from './routes/projet'
import { Route as PlanchePlancheIdRouteImport } from './routes/planche.$plancheId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliothequeRoute = BibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => rootRouteImport,
} as any)
const DonneesRoute = DonneesRouteImport.update({
  id: '/donnees',
  path: '/donnees',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetRoute = ProjetRouteImport.update({
  id: '/projet',
  path: '/projet',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanchePlancheIdRoute = PlanchePlancheIdRouteImport.update({
  id: '/planche/$plancheId',
  path: '/planche/$plancheId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/donnees': typeof DonneesRoute
  '/projet': typeof ProjetRoute
  '/planche/$plancheId': typeof PlanchePlancheIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/donnees': typeof DonneesRoute
  '/projet': typeof ProjetRoute
  '/planche/$plancheId': typeof PlanchePlancheIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/bibliotheque': typeof BibliothequeRoute
  '/donnees': typeof DonneesRoute
  '/projet': typeof ProjetRoute
  '/planche/$plancheId': typeof PlanchePlancheIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/bibliotheque'
    | '/donnees'
    | '/projet'
    | '/planche/$plancheId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/bibliotheque'
    | '/donnees'
    | '/projet'
    | '/planche/$plancheId'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/bibliotheque'
    | '/donnees'
    | '/projet'
    | '/planche/$plancheId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  BibliothequeRoute: typeof BibliothequeRoute
  DonneesRoute: typeof DonneesRoute
  ProjetRoute: typeof ProjetRoute
  PlanchePlancheIdRoute: typeof PlanchePlancheIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliotheque': {
      id: '/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof BibliothequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donnees': {
      id: '/donnees'
      path: '/donnees'
      fullPath: '/donnees'
      preLoaderRoute: typeof DonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projet': {
      id: '/projet'
      path: '/projet'
      fullPath: '/projet'
      preLoaderRoute: typeof ProjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planche/$plancheId': {
      id: '/planche/$plancheId'
      path: '/planche/$plancheId'
      fullPath: '/planche/$plancheId'
      preLoaderRoute: typeof PlanchePlancheIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  BibliothequeRoute: BibliothequeRoute,
  DonneesRoute: DonneesRoute,
  ProjetRoute: ProjetRoute,
  PlanchePlancheIdRoute: PlanchePlancheIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}